name: Build

on:
  push:
    branches: [master]

jobs:
  build-apk:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version:  '3.16.x'
    - run: flutter build apk --debug
    - uses: actions/upload-artifact@v1
      with:
        name: quickteam-apk
        path: build/app/outputs/apk/debug/app-debug.apk
